# Generated by Django 3.0.2 on 2020-01-27 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenShot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'Pending'), ('S', 'Success'), ('F', 'Failed'), ('R1', 'Retry #1'), ('R2', 'Retry #2'), ('R3', 'Retry #3')], default='N', max_length=2)),
            ],
        ),
    ]
