# Generated by Django 3.0.2 on 2020-01-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='is_fullpage',
            field=models.BooleanField(default=False),
        ),
    ]
