# Generated by Django 3.0.2 on 2020-01-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0004_screenshot_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
