# Generated by Django 3.0.2 on 2020-02-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0005_screenshot_raw_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='is_fullpage',
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
