# Generated by Django 3.0.2 on 2020-02-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0006_auto_20200204_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
