# Generated by Django 3.0.2 on 2020-02-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0007_screenshot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
