# Generated by Django 3.0.2 on 2020-02-09 16:05

import django.core.validators
from django.db import migrations, models
import shots.models
import shots.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0008_auto_20200207_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shots.models.hash_directory_path),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='url',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator(), shots.validators.validate_hostname_dns]),
        ),
    ]
