# Generated by Django 3.0.2 on 2020-02-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0010_auto_20200209_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='raw_html',
        ),
    ]
