# Generated by Django 3.0.2 on 2020-02-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0011_remove_screenshot_raw_html'),
    ]

    operations = [
    ]
