# Generated by Django 3.0.2 on 2020-02-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0012_remove_screenshot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='image_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
