# Generated by Django 3.0.2 on 2020-02-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0013_screenshot_image_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='base64_full',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='base64_thumb',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='format',
            field=models.CharField(choices=[('D', 'Desktop'), ('M', 'Mobile')], default='D', max_length=1),
        ),
    ]
