# Generated by Django 3.0.3 on 2020-02-28 10:53

import django.core.validators
from django.db import migrations, models
import shots.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0015_auto_20200213_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='callback_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator(), shots.validators.validate_hostname_dns]),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='created_with',
            field=models.CharField(choices=[('A', 'API'), ('B', 'Browser')], default='B', max_length=1),
        ),
    ]
