# Generated by Django 3.0.3 on 2020-03-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0016_auto_20200228_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='sleep_seconds',
            field=models.IntegerField(default=5),
        ),
    ]
