# Generated by Django 3.0.3 on 2020-03-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0017_screenshot_sleep_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='dpi',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
