# Generated by Django 3.0.3 on 2020-03-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0018_screenshot_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
