# Generated by Django 3.0.3 on 2020-03-15 20:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0019_auto_20200315_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='description',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='title',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
