# Generated by Django 3.0.3 on 2020-03-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0020_auto_20200315_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
