# Generated by Django 3.1.4 on 2020-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0022_remove_screenshot_image_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
